### ISSUE TITLE
Working on first installation, tried again and now it's stopped working.

### ISSUE THREAD

**Issue by Zazelus** [sakai135/wsl-vpnkit#130]
I'm using the Cisco AnyConnect VPN. Trying to ssh results in temporary failure in name resolution when running WSL 2 on Ubuntu and Linux.

So I went ahead and followed the readme using the latest release of wsl-vpnkit. It ended up working, but when I tried to walk it through with two others, I still had temporary failure in name resolution errors.

I figured I'd go ahead and start with a clean slate myself and run through the same steps again, but now it doesn't work. I feel as though I'm missing some essential step that I did the first time around. Anyone have a clue?

**Some details:**

I unregistered the wsl-vpnkit distribution, basically just followed the uninstallation steps on the readme. Went through the installation again, but when I start the distribution, it seems that startup.sh doesn't print anything to the terminal. Additionally, when I start the service and try to start it again, I don't get the message about the service already running. Before reinstallation, these messages would show on the terminal window.

**Comment by F21** [comment]
I also experienced a similar issue with wsl-vpnkit not working. I think this happens if you start the wsl2 distro before connecting to the vpn. My solution is to enable the vpn and then close all open wsl2 windows/terminals and open them again.

I also have this at the very top of my `.zshrc` to start the `wsl-vpnkit` service if it has not been started already:
```bash
if [[ -z $(wsl.exe -d wsl-vpnkit ps | grep wsl-vm) ]]; then
    wsl.exe -d wsl-vpnkit service wsl-vpnkit start
fi
```
