### ISSUE TITLE
wsl-vpnkit service change in 0.4.0

### ISSUE THREAD

**Issue by sakai135** [sakai135/wsl-vpnkit#202]
Hi all, 

I did not face this issue with WSL 1.1.3 and VPNKit 0.38. Even with the latest release of WSL 1.1.6 everything seems to work.

Anyway, why isn't it recommended aynmore to add the booting of VPNKit into ~/.profile and / or ~/.bashrc of WSL2 distro?
A colleague of mine tried it with latest release of VPNKit and during booting of his WSL2 distro he faced an issue telling us something like:
`could not find /bin/ash`... or `/bin/ash unknown command`... seems to be a typo in any shebang??

And we were also not able to setup the VPNKit with our WSL2 distro when starting it in the foreground...

As said, the old setup with 0.38 is working fine for me.

Best Valentin

_Originally posted by @ValentinTwin1206 in https://github.com/sakai135/wsl-vpnkit/issues/191#issuecomment-1491280392_

**Comment by sakai135** [comment]
@ValentinTwin1206 

Please see #199 for the reason of the switch to systemd. I also updated the release notes for v0.4.0 to highlight the change.

What were the specific issues you had in running wsl-vpnkit v0.4.0 in the foreground?

**Comment by pranaymodukuru** [comment]
Can you please also provide a source to setup the systemd to run the vpnkit in the background?

**Comment by ValentinTwin1206** [comment]
Hi @sakai135,

i will investigate the issue again and keep you updated!
Maybe I was doing something wrong.

Best Valentin

**Comment by ValentinTwin1206** [comment]
Hi @sakai135 ,

I have tested wsl-vpnkit 0.4.0 with latest release of WSL2 1.1.6 and found out following issues.

Locally, I have two distros installed:
1) Ubuntu 22.04 with systemd **not** enabled
2) Ubuntu 20.04 with systemd enabled

The distro with no systemd does not resolve addreses while the Ubuntu-20.04 with systemd support seems to run.
Do you want additional information / screenshots etc.?!

Does wsl-vpnkit requires systemd support on WSL2 distros? 

Best Valentin

**Comment by sakai135** [comment]
@ValentinTwin1206 Are you running `wsl-vpnkit` in the foreground and keeping it running when systemd is not enabled? systemd is not required, but you do need to keep `wsl-vpnkit` running in some way.

**Comment by ValentinTwin1206** [comment]
Hi @sakai135  and thanks for your quick responses :)

I have run `wsl-vpnkit` in foreground and afterwards started my Ubuntu distros (I also ensured that `~/.profile` is clean).
Running `sudo apt clean && sudo apt update` did not work out-of-the-box:
`Err:1 http://archive.ubuntu.com/ubuntu jammy InRelease
  Temporary failure resolving 'archive.ubuntu.com'
`
Then I activated a proxy for apt via `/etc/apt/apt.conf.d/70debconf` and above command worked fine.

I am wondering because I also have internal company repos in my apt sources where a proxy is actually not needed.
Those repos are also not reachable without proxy activated.

Running `cat /etc/wsl.conf` results in:
`
[boot]
systemd = true
[network]
generateResolvConf = false
`

I also have no `/etc/resolv.conf` file on my system.

So `wsl-vpnkit` + proxy is working fine for internal and external addresses.

Best Valentin

**Comment by sakai135** [comment]
If you have `generateResolvConf=false`, you probably need some `/etc/resolv.conf` for DNS. I am unsure of what your setup is, but I would suggest setting up your `/etc/resolv.conf` with your internal company DNS servers. This part should be unchanged from v0.3.

**Comment by ValentinTwin1206** [comment]
Hi @sakai135  I have rechecked my problem and you are right, I have to add company DNS servers and everything worked fine. I can resolve my company deb repos without HTTP proxy for APT.
To sum it up:
1) wsl-vpnkit started in foreground + /etc/resolv.conf providing company and google DNS + wsl.conf with `generateResolvConf=false` will make me work with company adresses
2) when I additionally add HTTP proxy for APT and tools like curl, I can also reach public adresses

Special case but maybe others will also run in the same problem..
